/**
* Copyright 2012-2017, Plotly, Inc.
* All rights reserved.
*
* This source code is licensed under the MIT license found in the
* LICENSE file in the root directory of this source tree.
*/


'use strict';

module.exports = {
    'circle': '●',
    'circle-open': '○',
    'square': '■',
    'square-open': '□',
    'diamond': '◆',
    'diamond-open': '◇',
    'cross': '✚',
    'x': '❌',
    'triangle-up': '▲',
    'triangle-up-open': '△',
    'triangle-down': '▼',
    'triangle-down-open': '▽',
    'triangle-left': '◄',
    'triangle-left-open': '◁',
    'triangle-right': '►',
    'triangle-right-open': '▷',
    'triangle-ne': '◥',
    'triangle-ne-open': '◹',
    'triangle-nw': '◤',
    'triangle-nw-open': '◸',
    'triangle-se': '◢',
    'triangle-se-open': '◿',
    'triangle-sw': '◣',
    'triangle-sw-open': '◺',
    'pentagon': '⬟',
    'pentagon-open': '⬠',
    'hexagon': '⬢',
    'hexagon-open': '⬡',
    'hexagon2': '⬣',
    'octagon': '⯃',
    'star': '★',
    'star-open': '☆',
    'hexagram': '🟌',
    'hexagram-open': '꙳',
    'star-triangle-up': '🟂',
    'star-triangle-down': '🟂',
    'star-square': '⯍',
    'star-diamond': '⯌',
    'star-square-open': '⯏',
    'star-diamond-open': '⯎',
    'diamond-tall': '♦',
    'diamond-tall-open': '♢',
    'diamond-wide': '▰',
    'diamond-wide-open': '▱',
    'hourglass': '⧗',
    'hourglass-open': '⧖',
    'bowtie': '⧓',
    'bowtie-open': '⋈',
    'circle-cross': '⨁',
    'circle-x': '⨂',
    'square-cross': '⊞',
    'square-x': '⊠',
    'diamond-cross': '⟠',
    'diamond-x': '❖',
    'cross-thin': '+',
    'x-thin': '╳',
    'asterisk': '✳',
    'hash': '⌗',
    'y-up': '⅄',
    'y-down': 'Y',
    'y-left': '≺',
    'y-right': '≻',
    'line-ew': '─',
    'line-ns': '│',
    'line-ne': '╱',
    'line-nw': '╲'
};
